# Generated by Django 5.0.7 on 2024-08-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_supportmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmember',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('closed', 'closed'), ('expired', 'expired'), ('resolved', 'resolved')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('closed', 'closed'), ('expired', 'expired'), ('resolved', 'resolved')], max_length=20),
        ),
    ]
