# Generated by Django 5.0.7 on 2024-08-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_supportmember_branch_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='Inquirer', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('user_status', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='branch_opened',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
