# Generated by Django 5.0.7 on 2024-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_message_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_message',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
