# Generated by Django 5.0.7 on 2024-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_supportmember_user_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='support_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
