# Generated by Django 5.0.7 on 2024-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_ticket_ticket_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inquirer',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inquirer',
            name='user_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inquirer',
            name='user_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supportmember',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supportmember',
            name='user_mode',
            field=models.CharField(blank=True, default='ticket_acceptance', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supportmember',
            name='user_status',
            field=models.CharField(blank=True, default='ticket_acceptance', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch_opened',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('closed', 'closed'), ('expired', 'expired'), ('resolved', 'resolved')], default='open', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='support_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_mode',
            field=models.CharField(blank=True, default='other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('closed', 'closed'), ('expired', 'expired'), ('resolved', 'resolved')], max_length=255),
        ),
    ]
