# Generated by Django 5.0.7 on 2024-08-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_branch_code_alter_inquirer_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
