# Generated by Django 5.0.7 on 2025-11-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ticket_inquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirer',
            name='phone_number',
            field=models.CharField(blank=True, default='2637', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inquirer',
            name='user_mode',
            field=models.CharField(blank=True, default='inquiry', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inquirer',
            name='user_status',
            field=models.CharField(blank=True, default='inquiry', max_length=255, null=True),
        ),
    ]
