# Generated by Django 5.0.7 on 2025-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0005_likertscaleanswer_text_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicdata',
            name='division',
            field=models.CharField(blank=True, choices=[('homelink_finance', 'Homelink Finance'), ('money_transfers', 'Money Transfers'), ('head_office', 'Head Office')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='location',
            field=models.CharField(blank=True, choices=[('harare', 'Harare'), ('kwekwe', 'Kwekwe'), ('gweru', 'Gweru'), ('bulawayo', 'Bulawayo'), ('masvingo', 'Masvingo')], max_length=50, null=True),
        ),
    ]
