# Generated by Django 5.0.7 on 2025-09-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0006_demographicdata_division_demographicdata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='age_group',
            field=models.CharField(choices=[('before_1966', 'Before 1966'), ('1966_1976', '1966-1976'), ('1977_1994', '1977-1994'), ('after_1994', 'After 1994')], default='20_below', max_length=50),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('relief', 'Relief')], default='permanent', max_length=50),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='department',
            field=models.CharField(choices=[('money_transfers', 'Money Transfers'), ('homelink_finance', 'Homelink Finance'), ('compliance', 'Compliance'), ('legal', 'Legal'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('projects', 'Projects'), ('mortgages', 'Mortgages'), ('security', 'Security'), ('human_capital', 'Human Capital'), ('ict', 'ICT')], default='MKT', max_length=100),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='designation',
            field=models.CharField(choices=[('director', 'Director'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('non_managerial', 'Non-managerial')], default='line_employees', max_length=50),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='highest_qualification',
            field=models.CharField(choices=[('o_level', 'O Level'), ('a_level', 'A Level'), ('diploma', 'Diploma/Professional Qualifications'), ('degree', 'Degree'), ('post_grad', 'Post Graduate')], default='o_level', max_length=50),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='work_experience',
            field=models.CharField(choices=[('less_than_1', 'Less than 1 year'), ('1_to_5', '1 to 5 years'), ('5_to_10', '5 to 10 years'), ('10_to_15', '10 to 15 years')], default='5_below', max_length=50),
        ),
        migrations.AlterField(
            model_name='likertscaleanswer',
            name='response',
            field=models.IntegerField(blank=True, choices=[(6, 'Strongly Agree'), (5, 'Agree'), (4, "Don't Know"), (3, 'Disagree'), (2, 'Strongly Disagree')], null=True),
        ),
    ]
