# Generated by Django 5.0.7 on 2025-09-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0007_alter_demographicdata_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertscaleanswer',
            name='text_response',
        ),
        migrations.AlterField(
            model_name='likertscaleanswer',
            name='response',
            field=models.IntegerField(blank=True, choices=[(1, 'Disagree very much'), (2, 'Disagree moderately'), (3, 'Disagree slightly'), (4, 'Agree slightly'), (5, 'Agree moderately'), (6, 'Agree very much')], null=True),
        ),
    ]
