# Generated by Django 5.0.7 on 2025-11-25 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0008_remove_likertscaleanswer_text_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('primary_color', models.CharField(default='#003366', max_length=7)),
                ('secondary_color', models.CharField(default='#FF6600', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demographicdata',
            name='division',
        ),
        migrations.RemoveField(
            model_name='demographicdata',
            name='location',
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='client_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='work_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='a_home.company'),
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_reports', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_home.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicDataold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('age_group', models.CharField(choices=[('before_1966', 'Before 1966'), ('1966_1976', '1966-1976'), ('1977_1994', '1977-1994'), ('after_1994', 'After 1994')], default='20_below', max_length=50)),
                ('work_experience', models.CharField(choices=[('less_than_1', 'Less than 1 year'), ('1_to_5', '1 to 5 years'), ('5_to_10', '5 to 10 years'), ('10_to_15', '10 to 15 years'), ('over_15', 'Over 15 years')], default='5_below', max_length=50)),
                ('highest_qualification', models.CharField(choices=[('o_level', 'O Level'), ('a_level', 'A Level'), ('diploma', 'Diploma/Professional Qualifications'), ('degree', 'Degree'), ('post_grad', 'Post Graduate')], default='o_level', max_length=50)),
                ('designation', models.CharField(choices=[('director', 'Director'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('non_managerial', 'Non-managerial')], default='line_employees', max_length=50)),
                ('department', models.CharField(choices=[('home_link_money_transfers', 'Homelink Money Transfers'), ('homelink_finance', 'Homelink Finance'), ('projects_and_mortgages', 'Projects And Mortgages'), ('finance_and_investments', 'Finance And Investments'), ('support_services', 'Support Services'), ('security', 'Security')], default='MKT', max_length=100)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('relief', 'Relief')], default='permanent', max_length=50)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('division', models.CharField(blank=True, choices=[('homelink_finance', 'Homelink Finance'), ('money_transfers', 'Money Transfers'), ('head_office', 'Head Office')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('harare', 'Harare'), ('kwekwe', 'Kwekwe'), ('gweru', 'Gweru'), ('bulawayo', 'Bulawayo'), ('mutare_and_rusape', 'Mutare and Rusape')], max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('general_satisfaction', 'General Satisfaction'), ('brand_awareness', 'Brand Awareness'), ('service_quality', 'Service Quality'), ('pricing_value', 'Pricing and Value'), ('vision_strategy', 'Vision and Strategy'), ('job_satisfaction', 'Job Satisfaction'), ('leadership', 'Leadership and People Management'), ('conditions_service', 'Conditions of Service'), ('communication', 'Communication'), ('learning_development', 'Learning Development'), ('organizational_culture', 'Organizational Culture'), ('nature_work', 'Nature of Work'), ('vigour', 'Vigour'), ('dedication', 'Dedication'), ('absorption', 'Absorption')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_home.company')),
            ],
            options={
                'ordering': ['company', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('response', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')])),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_home.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_home.surveyquestion')),
            ],
            options={
                'unique_together': {('user_id', 'question')},
            },
        ),
    ]
